# This workflow if for the section2 branch of the repo and not for the main branch.
name: Events Demo

# Trigger the workflow on push or pull request events to the main branch
on:
  pull_request:
    types:
      - opened
    branches:
      - section2
      - 'dev-*' # The single asterix means any characters other than slash
      - 'feat/**' # the double asterix allows for further slashes as a part of the remaining name
  workflow_dispatch:
    branches: [ section2 ]
  push:
    branches: [ section2 ]
    # paths-ignore:
    #   - '.github/workflows/*' # this means that even if other files changes, if even 1 file in the specified path changes, the action will not run
    paths:
      - 'src/*' # this means that the workflow will only be triggered if atleast one file from this path changes
      #Only one of path or path-ignore can be mentioned in a workflow file at a time

# Define the jobs that will be executed in the workflow 
jobs:
  # Job for linting the code using pylint
  lint:
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Define the steps to be executed in the job
    steps:
      # Checkout the code from the repository
      - name: Get Code From GitHub Repo
        uses: actions/checkout@v3
      # Set up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      # Install pylint
      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      # Run pylint on all Python files in the src directory
      - name: Run pylint
        run: pylint src/*.py

  # Job for running tests using pytest
  test:
    # This job depends on the successful completion of the lint job
    needs: lint
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Define the steps to be executed in the job
    steps:
      # Checkout the code from the repository
      - name: Get Code From GitHub Repo
        uses: actions/checkout@v3
      # Set up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      # Install pytest
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      # Run the tests
      - name: Run tests
        run: pytest

  # Job for building and deploying the application
  build-and-deploy:
    # This job depends on the successful completion of the test job
    needs: test
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Define the steps to be executed in the job
    steps:
      # Checkout the code from the repository
      - name: Get Code From GitHub Repo
        uses: actions/checkout@v3
      # Set up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      # Build and deploy the application
      - name: Build and Deploy
        run: |
          echo "Building the application..."
          # Add your build commands here
          echo "Deploying the application..."
          # Add your deploy commands here