name: Python CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: pytest

  build-and-deploy:  # You can choose a more specific name like 'deploy-to-pypi' or 'deploy-to-aws'
    needs: test  # This job depends on the 'test' job completing successfully
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build and Deploy  # Replace with your actual build and deploy commands
      run: |
        echo "Building the application..."
        # Add your build commands here, e.g., creating a package
        echo "Deploying the application..."
        # Add your deploy commands here, e.g., deploying to a server or a cloud platform